#------------------------------------------------------------------------------#
# Application YAML #
# inside ./src/main/resources/application.yml
#------------------------------------------------------------------------------#

# ENABLE for debug logging to show ConditionEvaluationReport :
debug: false

##---------------------------------------------------------------------------##
spring:


  ##---------------------------------------------------------------------------##
  ## Thymeleaf configuration:
#  thymeleaf:
#    cache: false
#    mode: HTML

  ##---------------------------------------------------------------------------##
  ## MongoDB
  data:
    mongodb:
      host: localhost
      database: dataSource


##---------------------------------------------------------------------------##
## Logging Configuration:
logging:
  level:
    io:
      baselogic:
        testloglevel: INFO

logging.level.org.hibernate.SQL: INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: DEBUG


##---------------------------------------------------------------------------##
