#------------------------------------------------------------------------------#
# Application YAML #
# inside ./src/main/resources/application.yml
#------------------------------------------------------------------------------#

# ENABLE for debug logging to show ConditionEvaluationReport :
debug: false

##---------------------------------------------------------------------------##
spring:


  ##---------------------------------------------------------------------------##
  ## MongoDB
  data:
    mongodb:
      host: localhost
      database: dataSource


##---------------------------------------------------------------------------##
## Logging Configuration:
logging:
  level:
    io:
      baselogic:
        testloglevel: INFO

##---------------------------------------------------------------------------##
