#------------------------------------------------------------------------------#
# Application YAML for TLS Profile #
# inside ./src/main/resources/application-tls.yml
#------------------------------------------------------------------------------#

##---------------------------------------------------------------------------##
# Configuring TLS in Tomcat in Spring Boot
server:
  port: 8443
  ssl:
    key-store: "classpath:keys/event_manager_clientauth.p12"
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: event_manager_client

    protocol: TLS
    enabled: true

    trust-store: "classpath:keys/event_manager.truststore"
    trust-store-password: changeit

##---------------------------------------------------------------------------##
