#------------------------------------------------------------------------------#
# Application YAML #
# inside ./src/main/resources/application.yml
#------------------------------------------------------------------------------#

# ENABLE for debug logging to show ConditionEvaluationReport :
debug: false

##---------------------------------------------------------------------------##
spring:


  # H2 Admin Console
  h2:
    console:
      enabled: true
      path: /h2

# R2DBC Configuration
#  r2dbc:
#    url: r2dbc:h2:mem:///dataSource?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
##    url: jdbc:h2:mem:dataSource
#    username: sa
#    password:
#    initialization-mode: always
#    generate-unique-name: false


##---------------------------------------------------------------------------##
## Actuators:
## https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-endpoints
## To expose all endpoints (be aware before exposing all endpoints for production)
# http://localhost:8080/actuator
# http://localhost:8080/actuator/beans
# http://localhost:8080/actuator/mappings
management:
  endpoints:
    web:
      #base-path: /admin/actuator
      exposure:
        include: '*'


##---------------------------------------------------------------------------##
## Logging Configuration:
logging:
  level:
    io:
      baselogic:
        testloglevel: INFO

logging.level.org.hibernate.SQL: INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: INFO


##---------------------------------------------------------------------------##
